#baseURL = "https://gardener.cloud"
baseURL = "https://gardener.cloud/"
languageCode = "en-US"
defaultContentLanguage = "en"
enableGitInfo = true

title = "Gardener Documentation"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
contentDir="content"

[params]
  # edit this for the final pull request to the real repo.  
  # in the .ci directory too.
  editURL = "https://github.com/gardener/documentation/edit/master/website/documentation/"
  issueURL = "https://github.com/gardener/documentation/issues"
  description = "Documentation for Gardener"
  author = "Andreas Herz"
  showVisitedLinks = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "gardener"

[outputs]
home = [ "HTML", "RSS", "JSON"]

