baseURL = "https://gardener.cloud/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Gardener"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
contentDir="content"
enableGitInfo = true

[markup] 
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  

[params]
  editURL = "https://github.com/gardener/documentation/edit/master/website/"
  issueURL = "https://github.com/gardener/documentation/issues"
  description = "Project Gardener Website"
  showVisitedLinks = true
  themeVariant = "gardener"

[outputs]
home = [ "HTML", "RSS", "JSON"]

